### ISSUE TITLE
Nice to have: search by LTLA codes

### ISSUE THREAD

**Issue by theosanderson** [theosanderson/covince#104]
E.g. E08000037

**Comment by richardgoater** [comment]
would be very redundant but it should work if they're added to the extra search terms e.g. https://github.com/theosanderson/covince/blob/master/public/data/area-search.json. Probably better to handle it as a special case on the UI 👍🏽

**Comment by theosanderson** [comment]
Yeah I was hoping that might do the trick - this was a note to self, but you reminded me quite how easy it was so done :) Thanks for setting up the infrastructure!
