### ISSUE TITLE
Provide initial date in lists.json

### ISSUE THREAD

**Issue by richardgoater** [theosanderson/covince#18]
Would be better than having a hard-coded date that's already out of sync 👍

**Comment by theosanderson** [comment]
Sounds good! https://github.com/theosanderson/covince/commit/eb4f219a552945e10736d52572f91fb7eb28424f

**Comment by theosanderson** [comment]
Reopening until I implement in backend

**Comment by theosanderson** [comment]
(and I guess til we actually implement on the front-end :) was just trying to unblock by picking the variable name)

**Comment by theosanderson** [comment]
Done
