### ISSUE TITLE
Separate out configgy stuff from data-y stuff in lists.json

### ISSUE THREAD

**Issue by theosanderson** [theosanderson/covince#64]
Two separate files, so that lists.json can be generated without knowing desired config?

**Comment by richardgoater** [comment]
yeah I agree. I almost renamed the whole file in a branch once, but good point that the lists are dependent on the pipeline 👍🏽

**Comment by richardgoater** [comment]
I would also suggest to remove the config from the tiles file and add it to the new config file, with the result that standard geojson can always be loaded from anywhere.

**Comment by theosanderson** [comment]
Yeah that sounds good - we just need accessors for the id and name
