### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by richardgoater** [theosanderson/covince#77]
Might be a better name for lists.json. Could be better to include map config here, and perhaps review/organise the existing keys.

**Comment by theosanderson** [comment]
`config.json` = the configgy bits of lists.json
`some_other_name_which_might_be_lists.json` = the lists of area names, etc.

**Comment by theosanderson** [comment]
(Rationale - the latter get written out by some automated pipeline)

**Comment by richardgoater** [comment]
Ah yeah, that sounds great 👍

**Comment by richardgoater** [comment]
Sorry this is a dupe of #64
